post_install() {
  KERNEL_VERSION=$(uname -r)
  depmod $KERNEL_VERSION

  echo ""
  echo "==> NOTE:"
  echo "==> If the modules do not load at boot, remember add in your rc.conf:"
  echo "==> MODULES=(lib80211 wl !b43 !ssb ...)"
  echo ""
  echo "==> And if you have problems with interfaces swapped, read the wiki:"
  echo "==> http://wiki.archlinux.org/index.php/Broadcom_BCM4312#Interfaces_swapped_every_time"

}

post_upgrade() {
  post_install
}
